export {default as Header} from './Header/Header'
export {default as Container} from './Container/Container'
export {default as Footer} from './Footer/Footer'
export {default as Offer} from './Offer/Offer'
export {default as Products} from './Products/Products'
